CLUBHOUSE_PROJECTS = [
    {"project": "Analytics", "id": 1444, "services": []},
    {"project": "Automated Testing", "id": 1492, "services": []},
    {"project": "Customer Service", "id": 568, "services": []},
    {"project": "Data Warehouse", "id": 1562, "services": []},
    {"project": "Driver", "id": 566, "services": []},
    {"project": "ETA and Tracking", "id": 564, "services": []},
    {"project": "Enterprise", "id": 34, "services": []},
    {"project": "Growth and Onboarding", "id": 35, "services": []},
    {"project": "Intercity", "id": 570, "services": []},
    {"project": "International", "id": 569, "services": []},
    {"project": "Operations", "id": 567, "services": []},
    {
        "project": "Payment and Pricing",
        "id": 565,
        "services": [
            "cashback",
            "coupons",
            "fares",
            "free-ride-service",
            "orders",
            "payments",
            "refunds",
            "user_subscription",
            "wallet",
        ],
    },
    {
        "project": "Platform",
        "id": 37,
        "services": [
            "auto_trip_creator",
            "canary-splitter",
            "gtfs",
            "rms_core",
            "tms",
            "user_auth",
            "user_authorization",
            "user_profile",
        ],
    },
    {"project": "Product Backlog", "id": 2090, "services": []},
    {"project": "Reporting", "id": 2402, "services": []},
    {"project": "Ride Experience", "id": 2, "services": []},
    {"project": "SRE", "id": 19, "services": []},
    {"project": "Vendor", "id": 36, "services": []},
    {"project": "X-Work", "id": 10, "services": []},
]
